services:
  frontend:
    env_file:
      - ./client/.env.local
    ports:
      - "3000:3000"
    build:
      dockerfile: ./client/
      target: dev
    networks:
      - marketsim
    depends_on:
      - api
    volumes:
      - ./client:/marketsim/client
  postgres:
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d marketsim -U postgres"]
      timeout: 5s
      retries: 3
    environment:
      POSTGRES_DB: marketsim
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    build: ./database/
    networks:
      - marketsim
  api:
    build:
      dockerfile: ./server/
      target: dev
    depends_on:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/"]
      timeout: 5s
      retries: 3
    env_file:
      - ./server/.env.development
    ports:
      - "3001:3001"
    networks:
      - marketsim
    volumes:
      - ./server:/marketsim/server
networks:
  marketsim:
    driver: bridge
volumes:
  marketsim:
    driver: local
