services:
  frontend:
    env_file:
      - ./client/.env.local
    ports:
      - "3000:3000"
    build: ./client/
    networks:
      - marketsim
    depends_on:
      - api
    volumes:
      - ./client:/marketsim/client
  postgres:
    env_file:
      - ./server/.env.development
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d marketsim -U postgres"]
      timeout: 5s
      retries: 3
    ports:
      - "5432:5432"
    build: ./database/
    networks:
      - marketsim
  api:
    build: ./server/
    depends_on:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/"]
      timeout: 5s
      retries: 3
    environment:
      POSTGRES_HOST: "sm_sim-v2-postgres-1"
      POSTGRES_PASSWORD: "password"
    ports:
      - "3001:3001"
    networks:
      - marketsim
    volumes:
      - ./server:/marketsim/server
networks:
  marketsim:
    driver: bridge
volumes:
  marketsim:
    driver: local
