services:
  frontend:
    env_file:
      - ./client/.env.local
    ports:
      - "3000:3000"
    build: ./client/
    networks:
      - marketsim
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./client:/marketsim/client
  postgres:
    env_file:
      - ./server/.env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d marketsim -U postgres"]
      interval: 5s
      timeout: 15s
      retries: 5
      start_period: 80s
    ports:
      - "5432:5432"
    build: ./database/
    networks:
      - marketsim
  api:
    build: ./server/
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/check"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 0s
    environment:
      POSTGRES_HOST: "sm_sim-v2-postgres-1"
      POSTGRES_PASSWORD: "password"
    ports:
      - "3001:3001"
    networks:
      - marketsim
networks:
  marketsim:
    name: marketsim
    external: true
volumes:
  marketsim:
