services:
  frontend:
    env_file:
      - ./client/.env.development
    ports:
      - "3000:3000"
    build: ./client/
    networks:
      - marketsim
    depends_on:
      api:
        condition: service_started
  postgres:
    env_file:
      - ./server/.env
    restart: always
    ports:
      - "5432:5432"
    build: ./server/postgres/
    networks:
        - marketsim
  api:
    build: ./server/
    depends_on:
      postgres:
        condition: service_started
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - "3001:3001"
    networks:
        - marketsim
networks:
  marketsim:
    name: marketsim
    external: true
