apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketsim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketsim
  template:
    metadata:
      labels:
        app: marketsim
    spec:
      containers:
        - name: sm-sim-v2-frontend
          image: dillonkmcquade/sm_sim-v2-frontend
          ports:
          - containerPort: 3000 
        - name: sm-sim-v2-api
          image: dillonkmcquade/sm_sim-v2-api
          ports:
          - containerPort: 3001 
        - name: sm-sim-v2-postgres
          image: dillonkmcquade/sm_sim-v2-postgres
          ports:
          - containerPort: 5432 
