BEGIN TRANSACTION;
CREATE TABLE transactions (
  id INTEGER PRIMARY KEY,
  user_id VARCHAR(30) NOT NULL,
  symbol VARCHAR(10) NOT NULL,
  price FLOAT NOT NULL,
  quantity INT NOT NULL,
  FOREIGN KEY (user_id)
  REFERENCES users(auth0_id)
);
COMMIT;
