services:
  postgres:
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    build: ./postgres
    networks:
        - marketsim
  api:
    build: .
    depends_on:
      - postgres
    stop_signal: SIGINT
    env_file:
      - .env
    ports:
      - "3001:3001"
    networks:
        - marketsim
networks:
  marketsim:
    name: marketsim
    external: true
